name: Java CI for Multi-Module Project

on:
  pull_request:
    branches:
      - 'develop'
    types:
      - closed  # Trigger only when a pull request is closed (merged)

jobs:
  # Job 1: Checkout, build, and test
  build-and-test:
    runs-on: ubuntu-latest

    # Add a condition to ensure the PR is merged and the branch starts with 'feature/builder-'
    if: github.event.pull_request.merged == true && (
      startsWith(github.head_ref, 'feature/builder-') ||
      startsWith(github.head_ref, 'feature/handler-'))

    steps:
      # Checkout the code from the develop branch
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Build and run tests
      - name: Build and test
        run: mvn -B package test

  # Job 2: Check and merge changes to release branches
  check-and-merge:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Checkout the code again for analysis
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Check if optimize-builder has changes and merge to release-builder
      - name: Check for changes in optimize-builder
        id: builder
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^optimize-builder/'; then
            echo "optimize-builder has changes"
            echo "::set-output name=builder_changed::true"
          else
            echo "optimize-builder has no changes"
            echo "::set-output name=builder_changed::false"
          fi
      
      # Check if optimize-handler has changes and merge to release-handler
      - name: Check for changes in optimize-handler
        id: handler
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^optimize-handler/'; then
            echo "optimize-handler has changes"
            echo "::set-output name=handler_changed::true"
          else
            echo "optimize-handler has no changes"
            echo "::set-output name=handler_changed::false"
          fi
          
      - name: Print changes
        run: |
          if [ "${{ steps.builder.outputs.builder_changed }}" == "true" ]; then
            echo "Changes detected in optimize-builder"
          fi
          if [ "${{ steps.handler.outputs.handler_changed }}" == "true" ]; then
            echo "Changes detected in optimize-handler"
          fi